# Análise exploratória de KPI's - Faturamento, Quantidade de Produtos Vendidos e Ticket Médio.

1- Importar a base de dados

2 - Calcular o faturamento de cada loja

3- Calcular a quantidade de produtos vendidos em cada loja

4- Calcular o ticket médio de cada loja

1 - Importação e visualização da base de dados

In [ ]:
import pandas as pd
tabela_vendas = pd.read_excel('/content/Vendas - Dez (2).xlsx')
display(tabela_vendas)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65014,2019-12-01,Shopping Morumbi,Sunga Listrado,5,114,570
1,65014,2019-12-01,Shopping Morumbi,Casaco Listrado,1,269,269
2,65016,2019-12-01,Iguatemi Campinas,Sapato Listrado,2,363,726
3,65016,2019-12-01,Iguatemi Campinas,Casaco,1,250,250
4,65017,2019-12-01,Shopping SP Market,Gorro Liso,3,92,276
...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

2 - Calcular o faturamento da loja

In [ ]:
tabela_faturamento = tabela_vendas[['ID Loja','Valor Final']].groupby('ID Loja').sum()    #slice e agrupamento das colunas por ID das Lojas
tabela_faturamento = tabela_faturamento.sort_values(by='Valor Final', ascending=False)    #Ordenar valores e fazer um Ranking de Faturamento do maior para o menor valor 
display(tabela_faturamento)

                                  Valor Final
ID Loja
Iguatemi Campinas                      149959
Rio Mar Recife                         139869
Shopping Recife                        131871
Salvador Shopping                      129156
Rio Mar Shopping Fortaleza             127890
Bourbon Shopping SP                    125850
Center Shopping Uberlândia             124960
Shopping Eldorado                      124339
Shopping Iguatemi Fortaleza            124182
Parque Dom Pedro Shopping              122055
Palladium Shopping Curitiba            120621
Shopping Morumbi                       117936
Shopping União de Osasco               116032
Shopping Vila Velha                    115896
Ribeirão Shopping                      112936
Passei das Águas Shopping              112089
Shopping SP Market                     110833
Shopping Ibirapuera                    107907
Shopping Midway Mall                   105269
Shopping Center Interlagos             103821
Iguatemi Esplanada                     103342
Shopping Barra                         103148
Norte Shopping                         101491
Novo Shopping Ribeirão Preto            99703
Shopping Center Leste Aricanduva        86156

3- Calcular a quantidade de produtos vendidos em cada loja

In [ ]:
tabela_qtd = tabela_vendas[['ID Loja','Quantidade']].groupby('ID Loja').sum() #agrupamento da coluna ID Loja e soma dos valores 
tabela_qtd = tabela_qtd.sort_values( by='Quantidade', ascending=False) #classificação do maior valor para o menor 
display(tabela_qtd)

                                  Quantidade
ID Loja
Rio Mar Recife                           767
Iguatemi Campinas                        707
Salvador Shopping                        669
Shopping Morumbi                         653
Shopping Recife                          652
Palladium Shopping Curitiba              645
Shopping Eldorado                        644
Shopping Iguatemi Fortaleza              640
Center Shopping Uberlândia               633
Rio Mar Shopping Fortaleza               629
Bourbon Shopping SP                      627
Passei das Águas Shopping                619
Shopping União de Osasco                 608
Shopping Vila Velha                      605
Ribeirão Shopping                        603
Parque Dom Pedro Shopping                599
Shopping SP Market                       584
Iguatemi Esplanada                       572
Shopping Barra                           571
Shopping Ibirapuera                      554
Shopping Midway Mall                     547
Norte Shopping                           546
Shopping Center Interlagos               545
Novo Shopping Ribeirão Preto             517
Shopping Center Leste Aricanduva         491

3 - Calcular o ticket médio de cada loja

In [ ]:
# ticket médio = faturamento/quantidade
ticket_medio = (tabela_faturamento['Valor Final']/tabela_qtd['Quantidade']) #segmentação da divisão por colunas 
ticket_medio.to_frame() #transforma em tabela

                                           0
ID Loja
Bourbon Shopping SP               200.717703
Center Shopping Uberlândia        197.409163
Iguatemi Campinas                 212.106082
Iguatemi Esplanada                180.667832
Norte Shopping                    185.880952
Novo Shopping Ribeirão Preto      192.849130
Palladium Shopping Curitiba       187.009302
Parque Dom Pedro Shopping         203.764608
Passei das Águas Shopping         181.080775
Ribeirão Shopping                 187.290216
Rio Mar Recife                    182.358540
Rio Mar Shopping Fortaleza        203.322734
Salvador Shopping                 193.058296
Shopping Barra                    180.644483
Shopping Center Interlagos        190.497248
Shopping Center Leste Aricanduva  175.470468
Shopping Eldorado                 193.072981
Shopping Ibirapuera               194.777978
Shopping Iguatemi Fortaleza       194.034375
Shopping Midway Mall              192.447898
Shopping Morumbi                  180.606432
Shopping Recife                   202.256135
Shopping SP Market                189.782534
Shopping União de Osasco          190.842105
Shopping Vila Velha               191.563636